/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/ping": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Ping
     * @description Do nothing.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Request fulfilled, nothing follows */
        204: {
          headers: {
            "Cache-Control"?: string;
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/playlist": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get playlist data
     * @description Get the current playlist data.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Request fulfilled, document follows */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["GetPlaylistResponse"];
          };
        };
        /** @description Request failed, resource not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "text/plain": string;
          };
        };
      };
    };
    /**
     * Update playlist data
     * @description Update the current playlist data.
     */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["PutPlaylistRequest"];
        };
      };
      responses: {
        /** @description Request fulfilled, document follows */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["PutPlaylistResponse"];
          };
        };
        /** @description Bad request syntax */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "text/plain": string;
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    GetPlaylistResponse: {
      /**
       * Format: uuid
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      id: string;
    };
    PutPlaylistRequest: {
      /**
       * Format: uuid
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      id: string;
    };
    PutPlaylistResponse: {
      /**
       * Format: uuid
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      id: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
