// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod";

export const PutPlaylistResponseSchema = z.object({
  id: z.uuid(),
});

export const PutPlaylistRequestSchema = z.object({
  id: z.uuid(),
});

export const GetPlaylistResponseSchema = z.object({
  id: z.uuid(),
});

export const GetPingRequestSchema = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Request fulfilled, nothing follows
 */
export const GetPingResponseSchema = z.void().register(z.globalRegistry, {
  description: "Request fulfilled, nothing follows",
});

export const GetPlaylistRequestSchema = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Request fulfilled, document follows
 */
export const GetPlaylistResponseSchema2 = GetPlaylistResponseSchema;

export const PutPlaylistRequestSchema2 = z.object({
  body: PutPlaylistRequestSchema,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Request fulfilled, document follows
 */
export const PutPlaylistResponseSchema2 = PutPlaylistResponseSchema;
