// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import {
  GetPingRequestSchema,
  GetPingResponseSchema,
  GetPlaylistRequestSchema,
  GetPlaylistResponseSchema2,
  PutPlaylistRequestSchema2,
  PutPlaylistResponseSchema2,
} from "./schemas";
import type {
  GetPingRequest,
  GetPingResponses,
  GetPlaylistErrors,
  GetPlaylistRequest,
  GetPlaylistResponses,
  PutPlaylistErrors,
  PutPlaylistRequest2,
  PutPlaylistResponses,
} from "./types";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

class HeyApiClient {
  protected client: Client;

  constructor(args: { client: Client }) {
    this.client = args.client;
  }
}

class HeyApiRegistry<T> {
  private readonly defaultKey = "default";

  private readonly instances: Map<string, T> = new Map();

  get(key?: string): T {
    const instance = this.instances.get(key ?? this.defaultKey);
    if (!instance) {
      throw new Error(
        `No SDK client found. Create one with "new Sdk()" to fix this error.`,
      );
    }
    return instance;
  }

  set(value: T, key?: string): void {
    this.instances.set(key ?? this.defaultKey, value);
  }
}

export class Sdk extends HeyApiClient {
  public static readonly __registry = new HeyApiRegistry<Sdk>();

  constructor(args: { client: Client; key?: string }) {
    super(args);
    Sdk.__registry.set(this, args.key);
  }

  /**
   * Ping
   *
   * Do nothing.
   */
  public getPing<ThrowOnError extends boolean = false>(
    options?: Options<GetPingRequest, ThrowOnError>,
  ) {
    return (options?.client ?? this.client).get<
      GetPingResponses,
      unknown,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await GetPingRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await GetPingResponseSchema.parseAsync(data),
      url: "/ping",
      ...options,
    });
  }

  /**
   * Get playlist data
   *
   * Get the current playlist data.
   */
  public getPlaylist<ThrowOnError extends boolean = false>(
    options?: Options<GetPlaylistRequest, ThrowOnError>,
  ) {
    return (options?.client ?? this.client).get<
      GetPlaylistResponses,
      GetPlaylistErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await GetPlaylistRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await GetPlaylistResponseSchema2.parseAsync(data),
      url: "/playlist",
      ...options,
    });
  }

  /**
   * Update playlist data
   *
   * Update the current playlist data.
   */
  public putPlaylist<ThrowOnError extends boolean = false>(
    options: Options<PutPlaylistRequest2, ThrowOnError>,
  ) {
    return (options.client ?? this.client).put<
      PutPlaylistResponses,
      PutPlaylistErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await PutPlaylistRequestSchema2.parseAsync(data),
      responseValidator: async (data) =>
        await PutPlaylistResponseSchema2.parseAsync(data),
      url: "/playlist",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}
