// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type PutPlaylistResponse = {
  id: string;
};

export type PutPlaylistRequest = {
  id: string;
};

export type GetPlaylistResponse = {
  id: string;
};

export type GetPingRequest = {
  body?: never;
  path?: never;
  query?: never;
  url: "/ping";
};

export type GetPingResponses = {
  /**
   * Request fulfilled, nothing follows
   */
  204: void;
};

export type GetPingResponse = GetPingResponses[keyof GetPingResponses];

export type GetPlaylistRequest = {
  body?: never;
  path?: never;
  query?: never;
  url: "/playlist";
};

export type GetPlaylistErrors = {
  /**
   * Request failed, resource not found
   */
  404: string;
};

export type GetPlaylistError = GetPlaylistErrors[keyof GetPlaylistErrors];

export type GetPlaylistResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: GetPlaylistResponse;
};

export type GetPlaylistResponse2 =
  GetPlaylistResponses[keyof GetPlaylistResponses];

export type PutPlaylistRequest2 = {
  body: PutPlaylistRequest;
  path?: never;
  query?: never;
  url: "/playlist";
};

export type PutPlaylistErrors = {
  /**
   * Bad request syntax
   */
  400: string;
};

export type PutPlaylistError = PutPlaylistErrors[keyof PutPlaylistErrors];

export type PutPlaylistResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: PutPlaylistResponse;
};

export type PutPlaylistResponse2 =
  PutPlaylistResponses[keyof PutPlaylistResponses];
