# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.2.0
_src_path: gh:radio-aktywne/template-app-next
accountname: radio-aktywne
appname: aster
description: Broadcast composing app 🧼
docs: true
docsurl: https://radio-aktywne.github.io/aster
envprefix: ASTER
imagename: apps/aster
keyprefix: aster
port: 10110
registry: true
releases: true
reponame: aster
repourl: https://github.com/radio-aktywne/aster
