// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod";

/**
 * Binding
 */
export const PlaylistsModelsBindingSchema = z.object({
  id: z.uuid().register(z.globalRegistry, {
    description: "Identifier of the binding.",
  }),
  playlistId: z.uuid().register(z.globalRegistry, {
    description: "Identifier of the playlist that the binding belongs to.",
  }),
  mediaId: z.uuid().register(z.globalRegistry, {
    description: "Identifier of the media that the binding belongs to.",
  }),
  rank: z.string().register(z.globalRegistry, {
    description: "Rank of the media in the binding.",
  }),
  playlist: z.unknown().register(z.globalRegistry, {
    description: "Playlist that the binding belongs to.",
  }),
  media: z.unknown().register(z.globalRegistry, {
    description: "Media that the binding belongs to.",
  }),
});

/**
 * Playlist
 */
export const PlaylistsModelsPlaylistSchema = z.object({
  id: z.uuid().register(z.globalRegistry, {
    description: "Identifier of the playlist.",
  }),
  name: z.string().register(z.globalRegistry, {
    description: "Name of the playlist.",
  }),
  bindings: z.optional(
    z.union([z.array(PlaylistsModelsBindingSchema), z.null()]),
  ),
});

/**
 * Binding
 */
export const MediaModelsBindingSchema = z.object({
  id: z.uuid().register(z.globalRegistry, {
    description: "Identifier of the binding.",
  }),
  playlistId: z.uuid().register(z.globalRegistry, {
    description: "Identifier of the playlist that the binding belongs to.",
  }),
  mediaId: z.uuid().register(z.globalRegistry, {
    description: "Identifier of the media that the binding belongs to.",
  }),
  rank: z.string().register(z.globalRegistry, {
    description: "Rank of the media in the binding.",
  }),
  playlist: z.unknown().register(z.globalRegistry, {
    description: "Playlist that the binding belongs to.",
  }),
  media: z.unknown().register(z.globalRegistry, {
    description: "Media that the binding belongs to.",
  }),
});

/**
 * Media
 */
export const MediaModelsMediaSchema = z.object({
  id: z.uuid().register(z.globalRegistry, {
    description: "Identifier of the media.",
  }),
  name: z.string().register(z.globalRegistry, {
    description: "Name of the media.",
  }),
  bindings: z.optional(z.union([z.array(MediaModelsBindingSchema), z.null()])),
});

/**
 * Playlist
 */
export const BindingsModelsPlaylistSchema = z.object({
  id: z.uuid().register(z.globalRegistry, {
    description: "Identifier of the playlist.",
  }),
  name: z.string().register(z.globalRegistry, {
    description: "Name of the playlist.",
  }),
  bindings: z.optional(z.union([z.array(z.unknown()), z.null()])),
});

/**
 * Media
 */
export const BindingsModelsMediaSchema = z.object({
  id: z.uuid().register(z.globalRegistry, {
    description: "Identifier of the media.",
  }),
  name: z.string().register(z.globalRegistry, {
    description: "Name of the media.",
  }),
  bindings: z.optional(z.union([z.array(z.unknown()), z.null()])),
});

/**
 * Binding
 */
export const BindingsModelsBindingSchema = z.object({
  id: z.uuid().register(z.globalRegistry, {
    description: "Identifier of the binding.",
  }),
  playlistId: z.uuid().register(z.globalRegistry, {
    description: "Identifier of the playlist that the binding belongs to.",
  }),
  mediaId: z.uuid().register(z.globalRegistry, {
    description: "Identifier of the media that the binding belongs to.",
  }),
  rank: z.string().register(z.globalRegistry, {
    description: "Rank of the media in the binding.",
  }),
  playlist: z.optional(z.union([BindingsModelsPlaylistSchema, z.null()])),
  media: z.optional(z.union([BindingsModelsMediaSchema, z.null()])),
});

/**
 * PlaylistUpdateInput
 *
 * Data to update a playlist.
 */
export const PlaylistUpdateInputSchema = z
  .object({
    id: z.optional(z.string()),
    name: z.optional(z.string()),
  })
  .register(z.globalRegistry, {
    description: "Data to update a playlist.",
  });

/**
 * PlaylistList
 */
export const PlaylistListSchema = z.object({
  count: z.int().register(z.globalRegistry, {
    description: "Total number of playlists that matched the query.",
  }),
  limit: z.optional(z.union([z.int(), z.null()])),
  offset: z.optional(z.union([z.int(), z.null()])),
  playlists: z.array(PlaylistsModelsPlaylistSchema).register(z.globalRegistry, {
    description: "Playlists that matched the request.",
  }),
});

/**
 * PlaylistCreateInput
 *
 * Data to create a playlist.
 */
export const PlaylistCreateInputSchema = z
  .object({
    id: z.optional(z.string()),
    name: z.string(),
  })
  .register(z.globalRegistry, {
    description: "Data to create a playlist.",
  });

/**
 * MediaUpdateInput
 *
 * Data to update media.
 */
export const MediaUpdateInputSchema = z
  .object({
    id: z.optional(z.string()),
    name: z.optional(z.string()),
  })
  .register(z.globalRegistry, {
    description: "Data to update media.",
  });

/**
 * MediaList
 */
export const MediaListSchema = z.object({
  count: z.int().register(z.globalRegistry, {
    description: "Total number of media that matched the query.",
  }),
  limit: z.optional(z.union([z.int(), z.null()])),
  offset: z.optional(z.union([z.int(), z.null()])),
  media: z.array(MediaModelsMediaSchema).register(z.globalRegistry, {
    description: "Media that matched the request.",
  }),
});

/**
 * MediaCreateInput
 *
 * Data to create media.
 */
export const MediaCreateInputSchema = z
  .object({
    id: z.optional(z.string()),
    name: z.string(),
  })
  .register(z.globalRegistry, {
    description: "Data to create media.",
  });

/**
 * BindingUpdateInput
 *
 * Data to update a binding.
 */
export const BindingUpdateInputSchema = z
  .object({
    id: z.optional(z.string()),
    rank: z.optional(z.string()),
  })
  .register(z.globalRegistry, {
    description: "Data to update a binding.",
  });

/**
 * BindingList
 */
export const BindingListSchema = z.object({
  count: z.int().register(z.globalRegistry, {
    description: "Total number of bindings that matched the query.",
  }),
  limit: z.optional(z.union([z.int(), z.null()])),
  offset: z.optional(z.union([z.int(), z.null()])),
  bindings: z.array(BindingsModelsBindingSchema).register(z.globalRegistry, {
    description: "Bindings that matched the request.",
  }),
});

/**
 * BindingCreateInput
 *
 * Data to create a binding.
 */
export const BindingCreateInputSchema = z
  .object({
    id: z.optional(z.string()),
    playlistId: z.string(),
    mediaId: z.string(),
    rank: z.string(),
  })
  .register(z.globalRegistry, {
    description: "Data to create a binding.",
  });

export const BindingsListRequestSchema = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      limit: z.optional(z.union([z.int().default(10), z.null()])).default(10),
      offset: z.optional(z.union([z.int(), z.null()])),
      where: z.optional(z.union([z.string(), z.null()])),
      include: z.optional(z.union([z.string(), z.null()])),
      order: z.optional(z.union([z.string(), z.null()])),
    }),
  ),
});

/**
 * Request fulfilled, document follows
 */
export const BindingsListResponseSchema = BindingListSchema;

export const BindingsCreateRequestSchema = z.object({
  body: BindingCreateInputSchema,
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      include: z.optional(z.union([z.string(), z.null()])),
    }),
  ),
});

/**
 * Document created, URL follows
 */
export const BindingsCreateResponseSchema = BindingsModelsBindingSchema;

export const BindingsIdDeleteRequestSchema = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the binding to delete.",
    }),
  }),
  query: z.optional(z.never()),
});

/**
 * Request fulfilled, nothing follows
 */
export const BindingsIdDeleteResponseSchema = z
  .void()
  .register(z.globalRegistry, {
    description: "Request fulfilled, nothing follows",
  });

export const BindingsIdGetRequestSchema = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the binding to get.",
    }),
  }),
  query: z.optional(
    z.object({
      include: z.optional(z.union([z.string(), z.null()])),
    }),
  ),
});

/**
 * Request fulfilled, document follows
 */
export const BindingsIdGetResponseSchema = BindingsModelsBindingSchema;

export const BindingsIdUpdateRequestSchema = z.object({
  body: BindingUpdateInputSchema,
  path: z.object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the binding to update.",
    }),
  }),
  query: z.optional(
    z.object({
      include: z.optional(z.union([z.string(), z.null()])),
    }),
  ),
});

/**
 * Request fulfilled, document follows
 */
export const BindingsIdUpdateResponseSchema = BindingsModelsBindingSchema;

export const MediaListRequestSchema = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      limit: z.optional(z.union([z.int().default(10), z.null()])).default(10),
      offset: z.optional(z.union([z.int(), z.null()])),
      where: z.optional(z.union([z.string(), z.null()])),
      include: z.optional(z.union([z.string(), z.null()])),
      order: z.optional(z.union([z.string(), z.null()])),
    }),
  ),
});

/**
 * Request fulfilled, document follows
 */
export const MediaListResponseSchema = MediaListSchema;

export const MediaCreateRequestSchema = z.object({
  body: MediaCreateInputSchema,
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      include: z.optional(z.union([z.string(), z.null()])),
    }),
  ),
});

/**
 * Document created, URL follows
 */
export const MediaCreateResponseSchema = MediaModelsMediaSchema;

export const MediaIdDeleteRequestSchema = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the media to delete.",
    }),
  }),
  query: z.optional(z.never()),
});

/**
 * Request fulfilled, nothing follows
 */
export const MediaIdDeleteResponseSchema = z.void().register(z.globalRegistry, {
  description: "Request fulfilled, nothing follows",
});

export const MediaIdGetRequestSchema = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the media to get.",
    }),
  }),
  query: z.optional(
    z.object({
      include: z.optional(z.union([z.string(), z.null()])),
    }),
  ),
});

/**
 * Request fulfilled, document follows
 */
export const MediaIdGetResponseSchema = MediaModelsMediaSchema;

export const MediaIdUpdateRequestSchema = z.object({
  body: MediaUpdateInputSchema,
  path: z.object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the media to update.",
    }),
  }),
  query: z.optional(
    z.object({
      include: z.optional(z.union([z.string(), z.null()])),
    }),
  ),
});

/**
 * Request fulfilled, document follows
 */
export const MediaIdUpdateResponseSchema = MediaModelsMediaSchema;

export const MediaIdContentDownloadRequestSchema = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the media to download content for.",
    }),
  }),
  query: z.optional(z.never()),
});

export const MediaIdContentHeaddownloadRequestSchema = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the media to get content headers for.",
    }),
  }),
  query: z.optional(z.never()),
});

export const MediaIdContentUploadRequestSchema = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the media to upload content for.",
    }),
  }),
  query: z.optional(z.never()),
  headers: z.object({
    "Content-Type": z.string().register(z.globalRegistry, {
      description: "Content type.",
    }),
  }),
});

/**
 * Request fulfilled, nothing follows
 */
export const MediaIdContentUploadResponseSchema = z
  .void()
  .register(z.globalRegistry, {
    description: "Request fulfilled, nothing follows",
  });

export const PingPingRequestSchema = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful ping.
 */
export const PingPingResponseSchema = z.void().register(z.globalRegistry, {
  description: "Successful ping.",
});

export const PingHeadpingRequestSchema = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful ping.
 */
export const PingHeadpingResponseSchema = z.void().register(z.globalRegistry, {
  description: "Successful ping.",
});

export const PlaylistsListRequestSchema = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      limit: z.optional(z.union([z.int().default(10), z.null()])).default(10),
      offset: z.optional(z.union([z.int(), z.null()])),
      where: z.optional(z.union([z.string(), z.null()])),
      include: z.optional(z.union([z.string(), z.null()])),
      order: z.optional(z.union([z.string(), z.null()])),
    }),
  ),
});

/**
 * Request fulfilled, document follows
 */
export const PlaylistsListResponseSchema = PlaylistListSchema;

export const PlaylistsCreateRequestSchema = z.object({
  body: PlaylistCreateInputSchema,
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      include: z.optional(z.union([z.string(), z.null()])),
    }),
  ),
});

/**
 * Document created, URL follows
 */
export const PlaylistsCreateResponseSchema = PlaylistsModelsPlaylistSchema;

export const PlaylistsIdDeleteRequestSchema = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the playlist to delete.",
    }),
  }),
  query: z.optional(z.never()),
});

/**
 * Request fulfilled, nothing follows
 */
export const PlaylistsIdDeleteResponseSchema = z
  .void()
  .register(z.globalRegistry, {
    description: "Request fulfilled, nothing follows",
  });

export const PlaylistsIdGetRequestSchema = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the playlist to get.",
    }),
  }),
  query: z.optional(
    z.object({
      include: z.optional(z.union([z.string(), z.null()])),
    }),
  ),
});

/**
 * Request fulfilled, document follows
 */
export const PlaylistsIdGetResponseSchema = PlaylistsModelsPlaylistSchema;

export const PlaylistsIdUpdateRequestSchema = z.object({
  body: PlaylistUpdateInputSchema,
  path: z.object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the playlist to update.",
    }),
  }),
  query: z.optional(
    z.object({
      include: z.optional(z.union([z.string(), z.null()])),
    }),
  ),
});

/**
 * Request fulfilled, document follows
 */
export const PlaylistsIdUpdateResponseSchema = PlaylistsModelsPlaylistSchema;

export const PlaylistsIdM3Um3uRequestSchema = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the playlist to get.",
    }),
  }),
  query: z.optional(z.never()),
});

/**
 * Request fulfilled, document follows
 */
export const PlaylistsIdM3Um3uResponseSchema = z
  .string()
  .register(z.globalRegistry, {
    description: "Request fulfilled, document follows",
  });

export const PlaylistsIdM3uHeadm3uRequestSchema = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the playlist to get.",
    }),
  }),
  query: z.optional(z.never()),
});

export const SseSubscribeRequestSchema = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Stream of Server-Sent Events.
 */
export const SseSubscribeResponseSchema = z
  .string()
  .register(z.globalRegistry, {
    description: "Stream of Server-Sent Events.",
  });
