// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

/**
 * _Binding_rank_OrderByInput
 */
export const PlaylistsModelsBindingRankOrderByInputSchema = z.object({
  rank: z.enum(["asc", "desc"]),
});

/**
 * _Binding_playlistId_OrderByInput
 */
export const PlaylistsModelsBindingPlaylistIdOrderByInputSchema = z.object({
  playlistId: z.enum(["asc", "desc"]),
});

/**
 * _Binding_mediaId_OrderByInput
 */
export const PlaylistsModelsBindingMediaIdOrderByInputSchema = z.object({
  mediaId: z.enum(["asc", "desc"]),
});

/**
 * _Binding_id_OrderByInput
 */
export const PlaylistsModelsBindingIdOrderByInputSchema = z.object({
  id: z.enum(["asc", "desc"]),
});

/**
 * _Binding_RelevanceInner
 */
export const PlaylistsModelsBindingRelevanceInnerSchema = z.object({
  fields: z.array(z.enum(["id", "playlistId", "mediaId", "rank"])),
  search: z.string(),
  sort: z.enum(["asc", "desc"]),
});

/**
 * _Binding_RelevanceOrderByInput
 */
export const PlaylistsModelsBindingRelevanceOrderByInputSchema = z.object({
  _relevance: PlaylistsModelsBindingRelevanceInnerSchema,
});

/**
 * _BindingWhereUnique_id_Input
 */
export const PlaylistsModelsBindingWhereUniqueIdInputSchema = z.object({
  id: z.string(),
});

/**
 * _BindingCompoundplaylistId_rankKeyInner
 */
export const PlaylistsModelsBindingCompoundplaylistIdRankKeyInnerSchema =
  z.object({
    playlistId: z.string(),
    rank: z.string(),
  });

/**
 * _BindingCompoundplaylistId_rankKey
 */
export const PlaylistsModelsBindingCompoundplaylistIdRankKeySchema = z.object({
  playlistidRank: PlaylistsModelsBindingCompoundplaylistIdRankKeyInnerSchema,
});

/**
 * StringFilter
 */
export const PlaylistsModelsStringFilterSchema = z.object({
  equals: z.optional(z.string()),
  notIn: z.optional(z.array(z.string())),
  lt: z.optional(z.string()),
  lte: z.optional(z.string()),
  gt: z.optional(z.string()),
  gte: z.optional(z.string()),
  contains: z.optional(z.string()),
  startswith: z.optional(z.string()),
  endswith: z.optional(z.string()),
  in: z.optional(z.array(z.string())),
  not: z.optional(
    z.union([z.string(), z.lazy((): any => PlaylistsModelsStringFilterSchema)]),
  ),
  mode: z.optional(z.enum(["default", "insensitive"])),
  search: z.optional(z.string()),
});

export const PlaylistsModelsUpdateRequestIdSchema = z.uuid();

/**
 * PlaylistUpdateManyMutationInput
 *
 * Arguments for updating many records
 */
export const PlaylistsModelsUpdateRequestDataSchema = z
  .object({
    id: z.optional(z.string()),
    name: z.optional(z.string()),
  })
  .register(z.globalRegistry, {
    description: "Arguments for updating many records",
  });

/**
 * _Playlist_name_OrderByInput
 */
export const PlaylistNameOrderByInputSchema = z.object({
  name: z.enum(["asc", "desc"]),
});

/**
 * _Playlist_id_OrderByInput
 */
export const PlaylistIdOrderByInputSchema = z.object({
  id: z.enum(["asc", "desc"]),
});

export const PlaylistOrderByInputSchema = z.union([
  PlaylistIdOrderByInputSchema,
  PlaylistNameOrderByInputSchema,
]);

export const PlaylistsModelsListRequestOrderSchema = z.union([
  PlaylistOrderByInputSchema,
  z.array(PlaylistOrderByInputSchema),
  z.null(),
]);

export const PlaylistsModelsListRequestOffsetSchema = z.union([
  z.int(),
  z.null(),
]);

export const PlaylistsModelsListRequestLimitSchema = z.union([
  z.int(),
  z.null(),
]);

export const PlaylistsModelsGetRequestIdSchema = z.uuid();

export const PlaylistsModelsDeleteRequestIdSchema = z.uuid();

/**
 * PlaylistCreateWithoutRelationsInput
 *
 * Required arguments to the Playlist create method, without relations
 */
export const PlaylistsModelsCreateRequestDataSchema = z
  .object({
    id: z.optional(z.string()),
    name: z.string(),
  })
  .register(z.globalRegistry, {
    description:
      "Required arguments to the Playlist create method, without relations",
  });

/**
 * _Binding_rank_OrderByInput
 */
export const MediaModelsBindingRankOrderByInputSchema = z.object({
  rank: z.enum(["asc", "desc"]),
});

/**
 * _Binding_playlistId_OrderByInput
 */
export const MediaModelsBindingPlaylistIdOrderByInputSchema = z.object({
  playlistId: z.enum(["asc", "desc"]),
});

/**
 * _Binding_mediaId_OrderByInput
 */
export const MediaModelsBindingMediaIdOrderByInputSchema = z.object({
  mediaId: z.enum(["asc", "desc"]),
});

/**
 * _Binding_id_OrderByInput
 */
export const MediaModelsBindingIdOrderByInputSchema = z.object({
  id: z.enum(["asc", "desc"]),
});

/**
 * _Binding_RelevanceInner
 */
export const MediaModelsBindingRelevanceInnerSchema = z.object({
  fields: z.array(z.enum(["id", "playlistId", "mediaId", "rank"])),
  search: z.string(),
  sort: z.enum(["asc", "desc"]),
});

/**
 * _Binding_RelevanceOrderByInput
 */
export const MediaModelsBindingRelevanceOrderByInputSchema = z.object({
  _relevance: MediaModelsBindingRelevanceInnerSchema,
});

/**
 * _BindingWhereUnique_id_Input
 */
export const MediaModelsBindingWhereUniqueIdInputSchema = z.object({
  id: z.string(),
});

/**
 * _BindingCompoundplaylistId_rankKeyInner
 */
export const MediaModelsBindingCompoundplaylistIdRankKeyInnerSchema = z.object({
  playlistId: z.string(),
  rank: z.string(),
});

/**
 * _BindingCompoundplaylistId_rankKey
 */
export const MediaModelsBindingCompoundplaylistIdRankKeySchema = z.object({
  playlistidRank: MediaModelsBindingCompoundplaylistIdRankKeyInnerSchema,
});

/**
 * StringFilter
 */
export const MediaModelsStringFilterSchema = z.object({
  equals: z.optional(z.string()),
  notIn: z.optional(z.array(z.string())),
  lt: z.optional(z.string()),
  lte: z.optional(z.string()),
  gt: z.optional(z.string()),
  gte: z.optional(z.string()),
  contains: z.optional(z.string()),
  startswith: z.optional(z.string()),
  endswith: z.optional(z.string()),
  in: z.optional(z.array(z.string())),
  not: z.optional(
    z.union([z.string(), z.lazy((): any => MediaModelsStringFilterSchema)]),
  ),
  mode: z.optional(z.enum(["default", "insensitive"])),
  search: z.optional(z.string()),
});

export const MediaModelsUpdateRequestIdSchema = z.uuid();

/**
 * MediaUpdateManyMutationInput
 *
 * Arguments for updating many records
 */
export const MediaModelsUpdateRequestDataSchema = z
  .object({
    id: z.optional(z.string()),
    name: z.optional(z.string()),
  })
  .register(z.globalRegistry, {
    description: "Arguments for updating many records",
  });

/**
 * _Media_name_OrderByInput
 */
export const MediaNameOrderByInputSchema = z.object({
  name: z.enum(["asc", "desc"]),
});

/**
 * _Media_id_OrderByInput
 */
export const MediaIdOrderByInputSchema = z.object({
  id: z.enum(["asc", "desc"]),
});

export const MediaOrderByInputSchema = z.union([
  MediaIdOrderByInputSchema,
  MediaNameOrderByInputSchema,
]);

export const MediaModelsListRequestOrderSchema = z.union([
  MediaOrderByInputSchema,
  z.array(MediaOrderByInputSchema),
  z.null(),
]);

export const MediaModelsListRequestOffsetSchema = z.union([z.int(), z.null()]);

export const MediaModelsListRequestLimitSchema = z.union([z.int(), z.null()]);

export const MediaModelsGetRequestIdSchema = z.uuid();

export const MediaModelsDeleteRequestIdSchema = z.uuid();

/**
 * MediaCreateWithoutRelationsInput
 *
 * Required arguments to the Media create method, without relations
 */
export const MediaModelsCreateRequestDataSchema = z
  .object({
    id: z.optional(z.string()),
    name: z.string(),
  })
  .register(z.globalRegistry, {
    description:
      "Required arguments to the Media create method, without relations",
  });

/**
 * _Binding_rank_OrderByInput
 */
export const BindingsModelsBindingRankOrderByInputSchema = z.object({
  rank: z.enum(["asc", "desc"]),
});

/**
 * _Binding_playlistId_OrderByInput
 */
export const BindingsModelsBindingPlaylistIdOrderByInputSchema = z.object({
  playlistId: z.enum(["asc", "desc"]),
});

/**
 * _Binding_mediaId_OrderByInput
 */
export const BindingsModelsBindingMediaIdOrderByInputSchema = z.object({
  mediaId: z.enum(["asc", "desc"]),
});

/**
 * _Binding_id_OrderByInput
 */
export const BindingsModelsBindingIdOrderByInputSchema = z.object({
  id: z.enum(["asc", "desc"]),
});

/**
 * _Binding_RelevanceInner
 */
export const BindingsModelsBindingRelevanceInnerSchema = z.object({
  fields: z.array(z.enum(["id", "playlistId", "mediaId", "rank"])),
  search: z.string(),
  sort: z.enum(["asc", "desc"]),
});

/**
 * _Binding_RelevanceOrderByInput
 */
export const BindingsModelsBindingRelevanceOrderByInputSchema = z.object({
  _relevance: BindingsModelsBindingRelevanceInnerSchema,
});

/**
 * _BindingWhereUnique_id_Input
 */
export const BindingsModelsBindingWhereUniqueIdInputSchema = z.object({
  id: z.string(),
});

/**
 * _BindingCompoundplaylistId_rankKeyInner
 */
export const BindingsModelsBindingCompoundplaylistIdRankKeyInnerSchema =
  z.object({
    playlistId: z.string(),
    rank: z.string(),
  });

/**
 * _BindingCompoundplaylistId_rankKey
 */
export const BindingsModelsBindingCompoundplaylistIdRankKeySchema = z.object({
  playlistidRank: BindingsModelsBindingCompoundplaylistIdRankKeyInnerSchema,
});

/**
 * StringFilter
 */
export const BindingsModelsStringFilterSchema = z.object({
  equals: z.optional(z.string()),
  notIn: z.optional(z.array(z.string())),
  lt: z.optional(z.string()),
  lte: z.optional(z.string()),
  gt: z.optional(z.string()),
  gte: z.optional(z.string()),
  contains: z.optional(z.string()),
  startswith: z.optional(z.string()),
  endswith: z.optional(z.string()),
  in: z.optional(z.array(z.string())),
  not: z.optional(
    z.union([z.string(), z.lazy((): any => BindingsModelsStringFilterSchema)]),
  ),
  mode: z.optional(z.enum(["default", "insensitive"])),
  search: z.optional(z.string()),
});

export const BindingsModelsUpdateRequestIdSchema = z.uuid();

/**
 * BindingUpdateManyMutationInput
 *
 * Arguments for updating many records
 */
export const BindingsModelsUpdateRequestDataSchema = z
  .object({
    id: z.optional(z.string()),
    rank: z.optional(z.string()),
  })
  .register(z.globalRegistry, {
    description: "Arguments for updating many records",
  });

export const BindingOrderByInputSchema = z.union([
  BindingsModelsBindingIdOrderByInputSchema,
  BindingsModelsBindingPlaylistIdOrderByInputSchema,
  BindingsModelsBindingMediaIdOrderByInputSchema,
  BindingsModelsBindingRankOrderByInputSchema,
]);

export const BindingsModelsListRequestOrderSchema = z.union([
  BindingOrderByInputSchema,
  z.array(BindingOrderByInputSchema),
  z.null(),
]);

export const BindingsModelsListRequestOffsetSchema = z.union([
  z.int(),
  z.null(),
]);

export const BindingsModelsListRequestLimitSchema = z.union([
  z.int(),
  z.null(),
]);

export const BindingsModelsGetRequestIdSchema = z.uuid();

export const BindingsModelsDeleteRequestIdSchema = z.uuid();

/**
 * BindingCreateInput
 *
 * Required arguments to the Binding create method.
 */
export const BindingsModelsCreateRequestDataSchema = z
  .object({
    id: z.optional(z.string()),
    playlistId: z.string().register(z.globalRegistry, {
      description: "Identifier of the playlist.",
    }),
    mediaId: z.string().register(z.globalRegistry, {
      description: "Identifier of the media.",
    }),
    rank: z.string().register(z.globalRegistry, {
      description: "Rank of the binding.",
    }),
  })
  .register(z.globalRegistry, {
    description: "Required arguments to the Binding create method.",
  });

export const UploadRequestTypeSchema = z.string();

export const UploadRequestIdSchema = z.uuid();

/**
 * Result
 *
 * Result of the test.
 */
export const TestResponseResultSchema = z
  .object({
    success: z.boolean().register(z.globalRegistry, {
      description: "Indicates if the test was successful.",
    }),
    message: z.string().register(z.globalRegistry, {
      description: "Message returned from the test.",
    }),
  })
  .register(z.globalRegistry, {
    description: "Result of the test.",
  });

/**
 * Parameters
 *
 * Parameters for testing.
 */
export const ParametersSchema = z
  .object({
    message: z.optional(z.union([z.string(), z.null()])).default(null),
  })
  .register(z.globalRegistry, {
    description: "Parameters for testing.",
  });

export const TestRequestParametersSchema = z.union([
  ParametersSchema,
  z.null(),
]);

export const M3uRequestIdSchema = z.uuid();

export const HeadM3uRequestIdSchema = z.uuid();

export const DownloadRequestIdSchema = z.uuid();

export const PlaylistsModelsUpdateRequestIncludeSchema = z.union([
  z.lazy((): any => PlaylistIncludeSchema),
  z.null(),
]);

/**
 * FindManyBindingArgsFromMedia
 *
 * Arguments for Media
 */
export const PlaylistsModelsFindManyBindingArgsFromMediaSchema = z
  .object({
    take: z.optional(z.int()),
    skip: z.optional(z.int()),
    orderBy: z.optional(
      z.union([
        PlaylistsModelsBindingIdOrderByInputSchema,
        PlaylistsModelsBindingPlaylistIdOrderByInputSchema,
        PlaylistsModelsBindingMediaIdOrderByInputSchema,
        PlaylistsModelsBindingRankOrderByInputSchema,
        PlaylistsModelsBindingRelevanceOrderByInputSchema,
        z.array(
          z.union([
            PlaylistsModelsBindingIdOrderByInputSchema,
            PlaylistsModelsBindingPlaylistIdOrderByInputSchema,
            PlaylistsModelsBindingMediaIdOrderByInputSchema,
            PlaylistsModelsBindingRankOrderByInputSchema,
            PlaylistsModelsBindingRelevanceOrderByInputSchema,
          ]),
        ),
      ]),
    ),
    get where() {
      return z.optional(
        z.lazy((): any => PlaylistsModelsBindingWhereInputSchema),
      );
    },
    cursor: z.optional(
      z.union([
        PlaylistsModelsBindingWhereUniqueIdInputSchema,
        PlaylistsModelsBindingCompoundplaylistIdRankKeySchema,
      ]),
    ),
    distinct: z.optional(
      z.array(z.enum(["id", "playlistId", "mediaId", "rank"])),
    ),
    get include() {
      return z.optional(
        z.lazy((): any => PlaylistsModelsBindingIncludeFromBindingSchema),
      );
    },
  })
  .register(z.globalRegistry, {
    description: "Arguments for Media",
  });

/**
 * BindingIncludeFromBinding
 *
 * Relational arguments for Binding
 */
export const PlaylistsModelsBindingIncludeFromBindingSchema = z
  .object({
    playlist: z.optional(
      z.union([
        z.boolean(),
        z.lazy((): any => PlaylistsModelsPlaylistArgsFromBindingSchema),
      ]),
    ),
    media: z.optional(
      z.union([
        z.boolean(),
        z.lazy((): any => PlaylistsModelsMediaArgsFromBindingSchema),
      ]),
    ),
  })
  .register(z.globalRegistry, {
    description: "Relational arguments for Binding",
  });

/**
 * BindingListRelationFilter
 */
export const PlaylistsModelsBindingListRelationFilterSchema = z.object({
  get some() {
    return z.optional(
      z.lazy((): any => PlaylistsModelsBindingWhereInputSchema),
    );
  },
  get none() {
    return z.optional(
      z.lazy((): any => PlaylistsModelsBindingWhereInputSchema),
    );
  },
  get every() {
    return z.optional(
      z.lazy((): any => PlaylistsModelsBindingWhereInputSchema),
    );
  },
});

/**
 * MediaWhereInput
 *
 * Media arguments for searching
 */
export const PlaylistsModelsMediaWhereInputSchema = z
  .object({
    id: z.optional(z.union([z.string(), PlaylistsModelsStringFilterSchema])),
    name: z.optional(z.union([z.string(), PlaylistsModelsStringFilterSchema])),
    bindings: z.optional(PlaylistsModelsBindingListRelationFilterSchema),
    get and() {
      return z.optional(
        z.array(z.lazy((): any => PlaylistsModelsMediaWhereInputSchema)),
      );
    },
    get or() {
      return z.optional(
        z.array(z.lazy((): any => PlaylistsModelsMediaWhereInputSchema)),
      );
    },
    get not() {
      return z.optional(
        z.array(z.lazy((): any => PlaylistsModelsMediaWhereInputSchema)),
      );
    },
  })
  .register(z.globalRegistry, {
    description: "Media arguments for searching",
  });

/**
 * MediaRelationFilter
 */
export const PlaylistsModelsMediaRelationFilterSchema = z.object({
  is: z.optional(PlaylistsModelsMediaWhereInputSchema),
  isNot: z.optional(PlaylistsModelsMediaWhereInputSchema),
});

/**
 * PlaylistWhereInput
 *
 * Playlist arguments for searching
 */
export const PlaylistsModelsPlaylistWhereInputSchema = z
  .object({
    id: z.optional(z.union([z.string(), PlaylistsModelsStringFilterSchema])),
    name: z.optional(z.union([z.string(), PlaylistsModelsStringFilterSchema])),
    bindings: z.optional(PlaylistsModelsBindingListRelationFilterSchema),
    get and() {
      return z.optional(
        z.array(z.lazy((): any => PlaylistsModelsPlaylistWhereInputSchema)),
      );
    },
    get or() {
      return z.optional(
        z.array(z.lazy((): any => PlaylistsModelsPlaylistWhereInputSchema)),
      );
    },
    get not() {
      return z.optional(
        z.array(z.lazy((): any => PlaylistsModelsPlaylistWhereInputSchema)),
      );
    },
  })
  .register(z.globalRegistry, {
    description: "Playlist arguments for searching",
  });

/**
 * PlaylistRelationFilter
 */
export const PlaylistsModelsPlaylistRelationFilterSchema = z.object({
  is: z.optional(PlaylistsModelsPlaylistWhereInputSchema),
  isNot: z.optional(PlaylistsModelsPlaylistWhereInputSchema),
});

/**
 * BindingWhereInput
 *
 * Binding arguments for searching
 */
export const PlaylistsModelsBindingWhereInputSchema = z
  .object({
    id: z.optional(z.union([z.string(), PlaylistsModelsStringFilterSchema])),
    playlistId: z.optional(
      z.union([z.string(), PlaylistsModelsStringFilterSchema]),
    ),
    mediaId: z.optional(
      z.union([z.string(), PlaylistsModelsStringFilterSchema]),
    ),
    rank: z.optional(z.union([z.string(), PlaylistsModelsStringFilterSchema])),
    playlist: z.optional(PlaylistsModelsPlaylistRelationFilterSchema),
    media: z.optional(PlaylistsModelsMediaRelationFilterSchema),
    get and() {
      return z.optional(
        z.array(z.lazy((): any => PlaylistsModelsBindingWhereInputSchema)),
      );
    },
    get or() {
      return z.optional(
        z.array(z.lazy((): any => PlaylistsModelsBindingWhereInputSchema)),
      );
    },
    get not() {
      return z.optional(
        z.array(z.lazy((): any => PlaylistsModelsBindingWhereInputSchema)),
      );
    },
  })
  .register(z.globalRegistry, {
    description: "Binding arguments for searching",
  });

/**
 * MediaIncludeFromMedia
 *
 * Relational arguments for Media
 */
export const PlaylistsModelsMediaIncludeFromMediaSchema = z
  .object({
    bindings: z.optional(
      z.union([z.boolean(), PlaylistsModelsFindManyBindingArgsFromMediaSchema]),
    ),
  })
  .register(z.globalRegistry, {
    description: "Relational arguments for Media",
  });

/**
 * MediaArgsFromBinding
 *
 * Arguments for Binding
 */
export const PlaylistsModelsMediaArgsFromBindingSchema = z
  .object({
    include: z.optional(PlaylistsModelsMediaIncludeFromMediaSchema),
  })
  .register(z.globalRegistry, {
    description: "Arguments for Binding",
  });

/**
 * FindManyBindingArgsFromPlaylist
 *
 * Arguments for Playlist
 */
export const PlaylistsModelsFindManyBindingArgsFromPlaylistSchema = z
  .object({
    take: z.optional(z.int()),
    skip: z.optional(z.int()),
    orderBy: z.optional(
      z.union([
        PlaylistsModelsBindingIdOrderByInputSchema,
        PlaylistsModelsBindingPlaylistIdOrderByInputSchema,
        PlaylistsModelsBindingMediaIdOrderByInputSchema,
        PlaylistsModelsBindingRankOrderByInputSchema,
        PlaylistsModelsBindingRelevanceOrderByInputSchema,
        z.array(
          z.union([
            PlaylistsModelsBindingIdOrderByInputSchema,
            PlaylistsModelsBindingPlaylistIdOrderByInputSchema,
            PlaylistsModelsBindingMediaIdOrderByInputSchema,
            PlaylistsModelsBindingRankOrderByInputSchema,
            PlaylistsModelsBindingRelevanceOrderByInputSchema,
          ]),
        ),
      ]),
    ),
    where: z.optional(PlaylistsModelsBindingWhereInputSchema),
    cursor: z.optional(
      z.union([
        PlaylistsModelsBindingWhereUniqueIdInputSchema,
        PlaylistsModelsBindingCompoundplaylistIdRankKeySchema,
      ]),
    ),
    distinct: z.optional(
      z.array(z.enum(["id", "playlistId", "mediaId", "rank"])),
    ),
    include: z.optional(PlaylistsModelsBindingIncludeFromBindingSchema),
  })
  .register(z.globalRegistry, {
    description: "Arguments for Playlist",
  });

/**
 * PlaylistIncludeFromPlaylist
 *
 * Relational arguments for Playlist
 */
export const PlaylistsModelsPlaylistIncludeFromPlaylistSchema = z
  .object({
    bindings: z.optional(
      z.union([
        z.boolean(),
        PlaylistsModelsFindManyBindingArgsFromPlaylistSchema,
      ]),
    ),
  })
  .register(z.globalRegistry, {
    description: "Relational arguments for Playlist",
  });

/**
 * PlaylistArgsFromBinding
 *
 * Arguments for Binding
 */
export const PlaylistsModelsPlaylistArgsFromBindingSchema = z
  .object({
    include: z.optional(PlaylistsModelsPlaylistIncludeFromPlaylistSchema),
  })
  .register(z.globalRegistry, {
    description: "Arguments for Binding",
  });

/**
 * PlaylistInclude
 *
 * Playlist relational arguments
 */
export const PlaylistIncludeSchema = z
  .object({
    bindings: z.optional(
      z.union([
        z.boolean(),
        PlaylistsModelsFindManyBindingArgsFromPlaylistSchema,
      ]),
    ),
  })
  .register(z.globalRegistry, {
    description: "Playlist relational arguments",
  });

/**
 * Playlist
 *
 * Playlist data.
 */
export const PlaylistsModelsPlaylistSchema = z
  .object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the playlist.",
    }),
    name: z.string().register(z.globalRegistry, {
      description: "Name of the playlist.",
    }),
    bindings: z.union([
      z.array(z.lazy((): any => PlaylistsModelsBindingSchema)),
      z.null(),
    ]),
  })
  .register(z.globalRegistry, {
    description: "Playlist data.",
  });

/**
 * Media
 *
 * Media data.
 */
export const PlaylistsModelsMediaSchema = z
  .object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the media.",
    }),
    name: z.string().register(z.globalRegistry, {
      description: "Name of the media.",
    }),
    bindings: z.union([
      z.array(z.lazy((): any => PlaylistsModelsBindingSchema)),
      z.null(),
    ]),
  })
  .register(z.globalRegistry, {
    description: "Media data.",
  });

/**
 * Binding
 *
 * Binding data.
 */
export const PlaylistsModelsBindingSchema = z
  .object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the binding.",
    }),
    playlistId: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the playlist that the binding belongs to.",
    }),
    mediaId: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the media that the binding belongs to.",
    }),
    rank: z.string().register(z.globalRegistry, {
      description: "Rank of the media in the binding.",
    }),
    playlist: z.union([PlaylistsModelsPlaylistSchema, z.null()]),
    media: z.union([PlaylistsModelsMediaSchema, z.null()]),
  })
  .register(z.globalRegistry, {
    description: "Binding data.",
  });

/**
 * PlaylistList
 *
 * List of playlists.
 */
export const PlaylistsModelsListResponseResultsSchema = z
  .object({
    count: z.int().register(z.globalRegistry, {
      description: "Total number of playlists that matched the query.",
    }),
    limit: z.union([z.int(), z.null()]),
    offset: z.union([z.int(), z.null()]),
    playlists: z
      .array(PlaylistsModelsPlaylistSchema)
      .register(z.globalRegistry, {
        description: "Playlists that matched the request.",
      }),
  })
  .register(z.globalRegistry, {
    description: "List of playlists.",
  });

export const PlaylistsModelsListRequestWhereSchema = z.union([
  PlaylistsModelsPlaylistWhereInputSchema,
  z.null(),
]);

export const PlaylistsModelsListRequestIncludeSchema = z.union([
  PlaylistIncludeSchema,
  z.null(),
]);

export const PlaylistsModelsGetRequestIncludeSchema = z.union([
  PlaylistIncludeSchema,
  z.null(),
]);

export const PlaylistsModelsCreateRequestIncludeSchema = z.union([
  PlaylistIncludeSchema,
  z.null(),
]);

export const MediaModelsUpdateRequestIncludeSchema = z.union([
  z.lazy((): any => MediaIncludeSchema),
  z.null(),
]);

/**
 * MediaIncludeFromMedia
 *
 * Relational arguments for Media
 */
export const MediaModelsMediaIncludeFromMediaSchema = z
  .object({
    bindings: z.optional(
      z.union([
        z.boolean(),
        z.lazy((): any => MediaModelsFindManyBindingArgsFromMediaSchema),
      ]),
    ),
  })
  .register(z.globalRegistry, {
    description: "Relational arguments for Media",
  });

/**
 * FindManyBindingArgsFromMedia
 *
 * Arguments for Media
 */
export const MediaModelsFindManyBindingArgsFromMediaSchema = z
  .object({
    take: z.optional(z.int()),
    skip: z.optional(z.int()),
    orderBy: z.optional(
      z.union([
        MediaModelsBindingIdOrderByInputSchema,
        MediaModelsBindingPlaylistIdOrderByInputSchema,
        MediaModelsBindingMediaIdOrderByInputSchema,
        MediaModelsBindingRankOrderByInputSchema,
        MediaModelsBindingRelevanceOrderByInputSchema,
        z.array(
          z.union([
            MediaModelsBindingIdOrderByInputSchema,
            MediaModelsBindingPlaylistIdOrderByInputSchema,
            MediaModelsBindingMediaIdOrderByInputSchema,
            MediaModelsBindingRankOrderByInputSchema,
            MediaModelsBindingRelevanceOrderByInputSchema,
          ]),
        ),
      ]),
    ),
    get where() {
      return z.optional(z.lazy((): any => MediaModelsBindingWhereInputSchema));
    },
    cursor: z.optional(
      z.union([
        MediaModelsBindingWhereUniqueIdInputSchema,
        MediaModelsBindingCompoundplaylistIdRankKeySchema,
      ]),
    ),
    distinct: z.optional(
      z.array(z.enum(["id", "playlistId", "mediaId", "rank"])),
    ),
    get include() {
      return z.optional(
        z.lazy((): any => MediaModelsBindingIncludeFromBindingSchema),
      );
    },
  })
  .register(z.globalRegistry, {
    description: "Arguments for Media",
  });

/**
 * MediaArgsFromBinding
 *
 * Arguments for Binding
 */
export const MediaModelsMediaArgsFromBindingSchema = z
  .object({
    include: z.optional(MediaModelsMediaIncludeFromMediaSchema),
  })
  .register(z.globalRegistry, {
    description: "Arguments for Binding",
  });

/**
 * FindManyBindingArgsFromPlaylist
 *
 * Arguments for Playlist
 */
export const MediaModelsFindManyBindingArgsFromPlaylistSchema = z
  .object({
    take: z.optional(z.int()),
    skip: z.optional(z.int()),
    orderBy: z.optional(
      z.union([
        MediaModelsBindingIdOrderByInputSchema,
        MediaModelsBindingPlaylistIdOrderByInputSchema,
        MediaModelsBindingMediaIdOrderByInputSchema,
        MediaModelsBindingRankOrderByInputSchema,
        MediaModelsBindingRelevanceOrderByInputSchema,
        z.array(
          z.union([
            MediaModelsBindingIdOrderByInputSchema,
            MediaModelsBindingPlaylistIdOrderByInputSchema,
            MediaModelsBindingMediaIdOrderByInputSchema,
            MediaModelsBindingRankOrderByInputSchema,
            MediaModelsBindingRelevanceOrderByInputSchema,
          ]),
        ),
      ]),
    ),
    get where() {
      return z.optional(z.lazy((): any => MediaModelsBindingWhereInputSchema));
    },
    cursor: z.optional(
      z.union([
        MediaModelsBindingWhereUniqueIdInputSchema,
        MediaModelsBindingCompoundplaylistIdRankKeySchema,
      ]),
    ),
    distinct: z.optional(
      z.array(z.enum(["id", "playlistId", "mediaId", "rank"])),
    ),
    get include() {
      return z.optional(
        z.lazy((): any => MediaModelsBindingIncludeFromBindingSchema),
      );
    },
  })
  .register(z.globalRegistry, {
    description: "Arguments for Playlist",
  });

/**
 * BindingIncludeFromBinding
 *
 * Relational arguments for Binding
 */
export const MediaModelsBindingIncludeFromBindingSchema = z
  .object({
    playlist: z.optional(
      z.union([
        z.boolean(),
        z.lazy((): any => MediaModelsPlaylistArgsFromBindingSchema),
      ]),
    ),
    media: z.optional(
      z.union([z.boolean(), MediaModelsMediaArgsFromBindingSchema]),
    ),
  })
  .register(z.globalRegistry, {
    description: "Relational arguments for Binding",
  });

/**
 * MediaWhereInput
 *
 * Media arguments for searching
 */
export const MediaModelsMediaWhereInputSchema = z
  .object({
    id: z.optional(z.union([z.string(), MediaModelsStringFilterSchema])),
    name: z.optional(z.union([z.string(), MediaModelsStringFilterSchema])),
    get bindings() {
      return z.optional(
        z.lazy((): any => MediaModelsBindingListRelationFilterSchema),
      );
    },
    get and() {
      return z.optional(
        z.array(z.lazy((): any => MediaModelsMediaWhereInputSchema)),
      );
    },
    get or() {
      return z.optional(
        z.array(z.lazy((): any => MediaModelsMediaWhereInputSchema)),
      );
    },
    get not() {
      return z.optional(
        z.array(z.lazy((): any => MediaModelsMediaWhereInputSchema)),
      );
    },
  })
  .register(z.globalRegistry, {
    description: "Media arguments for searching",
  });

/**
 * MediaRelationFilter
 */
export const MediaModelsMediaRelationFilterSchema = z.object({
  is: z.optional(MediaModelsMediaWhereInputSchema),
  isNot: z.optional(MediaModelsMediaWhereInputSchema),
});

/**
 * PlaylistWhereInput
 *
 * Playlist arguments for searching
 */
export const MediaModelsPlaylistWhereInputSchema = z
  .object({
    id: z.optional(z.union([z.string(), MediaModelsStringFilterSchema])),
    name: z.optional(z.union([z.string(), MediaModelsStringFilterSchema])),
    get bindings() {
      return z.optional(
        z.lazy((): any => MediaModelsBindingListRelationFilterSchema),
      );
    },
    get and() {
      return z.optional(
        z.array(z.lazy((): any => MediaModelsPlaylistWhereInputSchema)),
      );
    },
    get or() {
      return z.optional(
        z.array(z.lazy((): any => MediaModelsPlaylistWhereInputSchema)),
      );
    },
    get not() {
      return z.optional(
        z.array(z.lazy((): any => MediaModelsPlaylistWhereInputSchema)),
      );
    },
  })
  .register(z.globalRegistry, {
    description: "Playlist arguments for searching",
  });

/**
 * BindingListRelationFilter
 */
export const MediaModelsBindingListRelationFilterSchema = z.object({
  get some() {
    return z.optional(z.lazy((): any => MediaModelsBindingWhereInputSchema));
  },
  get none() {
    return z.optional(z.lazy((): any => MediaModelsBindingWhereInputSchema));
  },
  get every() {
    return z.optional(z.lazy((): any => MediaModelsBindingWhereInputSchema));
  },
});

/**
 * PlaylistRelationFilter
 */
export const MediaModelsPlaylistRelationFilterSchema = z.object({
  is: z.optional(MediaModelsPlaylistWhereInputSchema),
  isNot: z.optional(MediaModelsPlaylistWhereInputSchema),
});

/**
 * BindingWhereInput
 *
 * Binding arguments for searching
 */
export const MediaModelsBindingWhereInputSchema = z
  .object({
    id: z.optional(z.union([z.string(), MediaModelsStringFilterSchema])),
    playlistId: z.optional(
      z.union([z.string(), MediaModelsStringFilterSchema]),
    ),
    mediaId: z.optional(z.union([z.string(), MediaModelsStringFilterSchema])),
    rank: z.optional(z.union([z.string(), MediaModelsStringFilterSchema])),
    playlist: z.optional(MediaModelsPlaylistRelationFilterSchema),
    media: z.optional(MediaModelsMediaRelationFilterSchema),
    get and() {
      return z.optional(
        z.array(z.lazy((): any => MediaModelsBindingWhereInputSchema)),
      );
    },
    get or() {
      return z.optional(
        z.array(z.lazy((): any => MediaModelsBindingWhereInputSchema)),
      );
    },
    get not() {
      return z.optional(
        z.array(z.lazy((): any => MediaModelsBindingWhereInputSchema)),
      );
    },
  })
  .register(z.globalRegistry, {
    description: "Binding arguments for searching",
  });

/**
 * PlaylistIncludeFromPlaylist
 *
 * Relational arguments for Playlist
 */
export const MediaModelsPlaylistIncludeFromPlaylistSchema = z
  .object({
    bindings: z.optional(
      z.union([z.boolean(), MediaModelsFindManyBindingArgsFromPlaylistSchema]),
    ),
  })
  .register(z.globalRegistry, {
    description: "Relational arguments for Playlist",
  });

/**
 * PlaylistArgsFromBinding
 *
 * Arguments for Binding
 */
export const MediaModelsPlaylistArgsFromBindingSchema = z
  .object({
    include: z.optional(MediaModelsPlaylistIncludeFromPlaylistSchema),
  })
  .register(z.globalRegistry, {
    description: "Arguments for Binding",
  });

/**
 * MediaInclude
 *
 * Media relational arguments
 */
export const MediaIncludeSchema = z
  .object({
    bindings: z.optional(
      z.union([z.boolean(), MediaModelsFindManyBindingArgsFromMediaSchema]),
    ),
  })
  .register(z.globalRegistry, {
    description: "Media relational arguments",
  });

/**
 * Playlist
 *
 * Playlist data.
 */
export const MediaModelsPlaylistSchema = z
  .object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the playlist.",
    }),
    name: z.string().register(z.globalRegistry, {
      description: "Name of the playlist.",
    }),
    bindings: z.union([
      z.array(z.lazy((): any => MediaModelsBindingSchema)),
      z.null(),
    ]),
  })
  .register(z.globalRegistry, {
    description: "Playlist data.",
  });

/**
 * Binding
 *
 * Binding data.
 */
export const MediaModelsBindingSchema = z
  .object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the binding.",
    }),
    playlistId: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the playlist that the binding belongs to.",
    }),
    mediaId: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the media that the binding belongs to.",
    }),
    rank: z.string().register(z.globalRegistry, {
      description: "Rank of the media in the binding.",
    }),
    playlist: z.union([MediaModelsPlaylistSchema, z.null()]),
    media: z.union([z.lazy((): any => MediaModelsMediaSchema), z.null()]),
  })
  .register(z.globalRegistry, {
    description: "Binding data.",
  });

/**
 * Media
 *
 * Media data.
 */
export const MediaModelsMediaSchema = z
  .object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the media.",
    }),
    name: z.string().register(z.globalRegistry, {
      description: "Name of the media.",
    }),
    bindings: z.union([z.array(MediaModelsBindingSchema), z.null()]),
  })
  .register(z.globalRegistry, {
    description: "Media data.",
  });

/**
 * MediaList
 *
 * List of media.
 */
export const MediaModelsListResponseResultsSchema = z
  .object({
    count: z.int().register(z.globalRegistry, {
      description: "Total number of media that matched the query.",
    }),
    limit: z.union([z.int(), z.null()]),
    offset: z.union([z.int(), z.null()]),
    media: z.array(MediaModelsMediaSchema).register(z.globalRegistry, {
      description: "Media that matched the request.",
    }),
  })
  .register(z.globalRegistry, {
    description: "List of media.",
  });

export const MediaModelsListRequestWhereSchema = z.union([
  MediaModelsMediaWhereInputSchema,
  z.null(),
]);

export const MediaModelsListRequestIncludeSchema = z.union([
  MediaIncludeSchema,
  z.null(),
]);

export const MediaModelsGetRequestIncludeSchema = z.union([
  MediaIncludeSchema,
  z.null(),
]);

export const MediaModelsCreateRequestIncludeSchema = z.union([
  MediaIncludeSchema,
  z.null(),
]);

export const BindingsModelsUpdateRequestIncludeSchema = z.union([
  z.lazy((): any => BindingIncludeSchema),
  z.null(),
]);

/**
 * FindManyBindingArgsFromMedia
 *
 * Arguments for Media
 */
export const BindingsModelsFindManyBindingArgsFromMediaSchema = z
  .object({
    take: z.optional(z.int()),
    skip: z.optional(z.int()),
    orderBy: z.optional(
      z.union([
        BindingsModelsBindingIdOrderByInputSchema,
        BindingsModelsBindingPlaylistIdOrderByInputSchema,
        BindingsModelsBindingMediaIdOrderByInputSchema,
        BindingsModelsBindingRankOrderByInputSchema,
        BindingsModelsBindingRelevanceOrderByInputSchema,
        z.array(
          z.union([
            BindingsModelsBindingIdOrderByInputSchema,
            BindingsModelsBindingPlaylistIdOrderByInputSchema,
            BindingsModelsBindingMediaIdOrderByInputSchema,
            BindingsModelsBindingRankOrderByInputSchema,
            BindingsModelsBindingRelevanceOrderByInputSchema,
          ]),
        ),
      ]),
    ),
    get where() {
      return z.optional(
        z.lazy((): any => BindingsModelsBindingWhereInputSchema),
      );
    },
    cursor: z.optional(
      z.union([
        BindingsModelsBindingWhereUniqueIdInputSchema,
        BindingsModelsBindingCompoundplaylistIdRankKeySchema,
      ]),
    ),
    distinct: z.optional(
      z.array(z.enum(["id", "playlistId", "mediaId", "rank"])),
    ),
    get include() {
      return z.optional(
        z.lazy((): any => BindingsModelsBindingIncludeFromBindingSchema),
      );
    },
  })
  .register(z.globalRegistry, {
    description: "Arguments for Media",
  });

/**
 * BindingIncludeFromBinding
 *
 * Relational arguments for Binding
 */
export const BindingsModelsBindingIncludeFromBindingSchema = z
  .object({
    playlist: z.optional(
      z.union([
        z.boolean(),
        z.lazy((): any => BindingsModelsPlaylistArgsFromBindingSchema),
      ]),
    ),
    media: z.optional(
      z.union([
        z.boolean(),
        z.lazy((): any => BindingsModelsMediaArgsFromBindingSchema),
      ]),
    ),
  })
  .register(z.globalRegistry, {
    description: "Relational arguments for Binding",
  });

/**
 * MediaWhereInput
 *
 * Media arguments for searching
 */
export const BindingsModelsMediaWhereInputSchema = z
  .object({
    id: z.optional(z.union([z.string(), BindingsModelsStringFilterSchema])),
    name: z.optional(z.union([z.string(), BindingsModelsStringFilterSchema])),
    get bindings() {
      return z.optional(
        z.lazy((): any => BindingsModelsBindingListRelationFilterSchema),
      );
    },
    get and() {
      return z.optional(
        z.array(z.lazy((): any => BindingsModelsMediaWhereInputSchema)),
      );
    },
    get or() {
      return z.optional(
        z.array(z.lazy((): any => BindingsModelsMediaWhereInputSchema)),
      );
    },
    get not() {
      return z.optional(
        z.array(z.lazy((): any => BindingsModelsMediaWhereInputSchema)),
      );
    },
  })
  .register(z.globalRegistry, {
    description: "Media arguments for searching",
  });

/**
 * BindingWhereInput
 *
 * Binding arguments for searching
 */
export const BindingsModelsBindingWhereInputSchema = z
  .object({
    id: z.optional(z.union([z.string(), BindingsModelsStringFilterSchema])),
    playlistId: z.optional(
      z.union([z.string(), BindingsModelsStringFilterSchema]),
    ),
    mediaId: z.optional(
      z.union([z.string(), BindingsModelsStringFilterSchema]),
    ),
    rank: z.optional(z.union([z.string(), BindingsModelsStringFilterSchema])),
    get playlist() {
      return z.optional(
        z.lazy((): any => BindingsModelsPlaylistRelationFilterSchema),
      );
    },
    get media() {
      return z.optional(
        z.lazy((): any => BindingsModelsMediaRelationFilterSchema),
      );
    },
    get and() {
      return z.optional(
        z.array(z.lazy((): any => BindingsModelsBindingWhereInputSchema)),
      );
    },
    get or() {
      return z.optional(
        z.array(z.lazy((): any => BindingsModelsBindingWhereInputSchema)),
      );
    },
    get not() {
      return z.optional(
        z.array(z.lazy((): any => BindingsModelsBindingWhereInputSchema)),
      );
    },
  })
  .register(z.globalRegistry, {
    description: "Binding arguments for searching",
  });

/**
 * MediaRelationFilter
 */
export const BindingsModelsMediaRelationFilterSchema = z.object({
  is: z.optional(BindingsModelsMediaWhereInputSchema),
  isNot: z.optional(BindingsModelsMediaWhereInputSchema),
});

/**
 * BindingListRelationFilter
 */
export const BindingsModelsBindingListRelationFilterSchema = z.object({
  some: z.optional(BindingsModelsBindingWhereInputSchema),
  none: z.optional(BindingsModelsBindingWhereInputSchema),
  every: z.optional(BindingsModelsBindingWhereInputSchema),
});

/**
 * PlaylistWhereInput
 *
 * Playlist arguments for searching
 */
export const BindingsModelsPlaylistWhereInputSchema = z
  .object({
    id: z.optional(z.union([z.string(), BindingsModelsStringFilterSchema])),
    name: z.optional(z.union([z.string(), BindingsModelsStringFilterSchema])),
    bindings: z.optional(BindingsModelsBindingListRelationFilterSchema),
    get and() {
      return z.optional(
        z.array(z.lazy((): any => BindingsModelsPlaylistWhereInputSchema)),
      );
    },
    get or() {
      return z.optional(
        z.array(z.lazy((): any => BindingsModelsPlaylistWhereInputSchema)),
      );
    },
    get not() {
      return z.optional(
        z.array(z.lazy((): any => BindingsModelsPlaylistWhereInputSchema)),
      );
    },
  })
  .register(z.globalRegistry, {
    description: "Playlist arguments for searching",
  });

/**
 * PlaylistRelationFilter
 */
export const BindingsModelsPlaylistRelationFilterSchema = z.object({
  is: z.optional(BindingsModelsPlaylistWhereInputSchema),
  isNot: z.optional(BindingsModelsPlaylistWhereInputSchema),
});

/**
 * MediaIncludeFromMedia
 *
 * Relational arguments for Media
 */
export const BindingsModelsMediaIncludeFromMediaSchema = z
  .object({
    bindings: z.optional(
      z.union([z.boolean(), BindingsModelsFindManyBindingArgsFromMediaSchema]),
    ),
  })
  .register(z.globalRegistry, {
    description: "Relational arguments for Media",
  });

/**
 * MediaArgsFromBinding
 *
 * Arguments for Binding
 */
export const BindingsModelsMediaArgsFromBindingSchema = z
  .object({
    include: z.optional(BindingsModelsMediaIncludeFromMediaSchema),
  })
  .register(z.globalRegistry, {
    description: "Arguments for Binding",
  });

/**
 * PlaylistArgsFromBinding
 *
 * Arguments for Binding
 */
export const BindingsModelsPlaylistArgsFromBindingSchema = z
  .object({
    get include() {
      return z.optional(
        z.lazy((): any => BindingsModelsPlaylistIncludeFromPlaylistSchema),
      );
    },
  })
  .register(z.globalRegistry, {
    description: "Arguments for Binding",
  });

/**
 * FindManyBindingArgsFromPlaylist
 *
 * Arguments for Playlist
 */
export const BindingsModelsFindManyBindingArgsFromPlaylistSchema = z
  .object({
    take: z.optional(z.int()),
    skip: z.optional(z.int()),
    orderBy: z.optional(
      z.union([
        BindingsModelsBindingIdOrderByInputSchema,
        BindingsModelsBindingPlaylistIdOrderByInputSchema,
        BindingsModelsBindingMediaIdOrderByInputSchema,
        BindingsModelsBindingRankOrderByInputSchema,
        BindingsModelsBindingRelevanceOrderByInputSchema,
        z.array(
          z.union([
            BindingsModelsBindingIdOrderByInputSchema,
            BindingsModelsBindingPlaylistIdOrderByInputSchema,
            BindingsModelsBindingMediaIdOrderByInputSchema,
            BindingsModelsBindingRankOrderByInputSchema,
            BindingsModelsBindingRelevanceOrderByInputSchema,
          ]),
        ),
      ]),
    ),
    where: z.optional(BindingsModelsBindingWhereInputSchema),
    cursor: z.optional(
      z.union([
        BindingsModelsBindingWhereUniqueIdInputSchema,
        BindingsModelsBindingCompoundplaylistIdRankKeySchema,
      ]),
    ),
    distinct: z.optional(
      z.array(z.enum(["id", "playlistId", "mediaId", "rank"])),
    ),
    include: z.optional(BindingsModelsBindingIncludeFromBindingSchema),
  })
  .register(z.globalRegistry, {
    description: "Arguments for Playlist",
  });

/**
 * PlaylistIncludeFromPlaylist
 *
 * Relational arguments for Playlist
 */
export const BindingsModelsPlaylistIncludeFromPlaylistSchema = z
  .object({
    bindings: z.optional(
      z.union([
        z.boolean(),
        BindingsModelsFindManyBindingArgsFromPlaylistSchema,
      ]),
    ),
  })
  .register(z.globalRegistry, {
    description: "Relational arguments for Playlist",
  });

/**
 * BindingInclude
 *
 * Binding relational arguments
 */
export const BindingIncludeSchema = z
  .object({
    playlist: z.optional(
      z.union([z.boolean(), BindingsModelsPlaylistArgsFromBindingSchema]),
    ),
    media: z.optional(
      z.union([z.boolean(), BindingsModelsMediaArgsFromBindingSchema]),
    ),
  })
  .register(z.globalRegistry, {
    description: "Binding relational arguments",
  });

/**
 * Playlist
 *
 * Playlist data.
 */
export const BindingsModelsPlaylistSchema = z
  .object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the playlist.",
    }),
    name: z.string().register(z.globalRegistry, {
      description: "Name of the playlist.",
    }),
    bindings: z.union([
      z.array(z.lazy((): any => BindingsModelsBindingSchema)),
      z.null(),
    ]),
  })
  .register(z.globalRegistry, {
    description: "Playlist data.",
  });

/**
 * Binding
 *
 * Binding data.
 */
export const BindingsModelsBindingSchema = z
  .object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the binding.",
    }),
    playlistId: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the playlist that the binding belongs to.",
    }),
    mediaId: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the media that the binding belongs to.",
    }),
    rank: z.string().register(z.globalRegistry, {
      description: "Rank of the media in the binding.",
    }),
    playlist: z.union([BindingsModelsPlaylistSchema, z.null()]),
    media: z.union([z.lazy((): any => BindingsModelsMediaSchema), z.null()]),
  })
  .register(z.globalRegistry, {
    description: "Binding data.",
  });

/**
 * Media
 *
 * Media data.
 */
export const BindingsModelsMediaSchema = z
  .object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the media.",
    }),
    name: z.string().register(z.globalRegistry, {
      description: "Name of the media.",
    }),
    bindings: z.union([z.array(BindingsModelsBindingSchema), z.null()]),
  })
  .register(z.globalRegistry, {
    description: "Media data.",
  });

/**
 * BindingList
 *
 * List of bindings.
 */
export const BindingsModelsListResponseResultsSchema = z
  .object({
    count: z.int().register(z.globalRegistry, {
      description: "Total number of bindings that matched the query.",
    }),
    limit: z.union([z.int(), z.null()]),
    offset: z.union([z.int(), z.null()]),
    bindings: z.array(BindingsModelsBindingSchema).register(z.globalRegistry, {
      description: "Bindings that matched the request.",
    }),
  })
  .register(z.globalRegistry, {
    description: "List of bindings.",
  });

export const BindingsModelsListRequestWhereSchema = z.union([
  BindingsModelsBindingWhereInputSchema,
  z.null(),
]);

export const BindingsModelsListRequestIncludeSchema = z.union([
  BindingIncludeSchema,
  z.null(),
]);

export const BindingsModelsGetRequestIncludeSchema = z.union([
  BindingIncludeSchema,
  z.null(),
]);

export const BindingsModelsCreateRequestIncludeSchema = z.union([
  BindingIncludeSchema,
  z.null(),
]);

/**
 * Playlist
 *
 * Playlist data.
 */
export const GetResponsePlaylistSchema = z
  .object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the playlist.",
    }),
    name: z.string().register(z.globalRegistry, {
      description: "Name of the playlist.",
    }),
    bindings: z.union([z.array(PlaylistsModelsBindingSchema), z.null()]),
  })
  .register(z.globalRegistry, {
    description: "Playlist data.",
  });

/**
 * Media
 *
 * Media data.
 */
export const GetResponseMediaSchema = z
  .object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the media.",
    }),
    name: z.string().register(z.globalRegistry, {
      description: "Name of the media.",
    }),
    bindings: z.union([z.array(MediaModelsBindingSchema), z.null()]),
  })
  .register(z.globalRegistry, {
    description: "Media data.",
  });

/**
 * Binding
 *
 * Binding data.
 */
export const GetResponseBindingSchema = z
  .object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the binding.",
    }),
    playlistId: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the playlist that the binding belongs to.",
    }),
    mediaId: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the media that the binding belongs to.",
    }),
    rank: z.string().register(z.globalRegistry, {
      description: "Rank of the media in the binding.",
    }),
    playlist: z.union([BindingsModelsPlaylistSchema, z.null()]),
    media: z.union([BindingsModelsMediaSchema, z.null()]),
  })
  .register(z.globalRegistry, {
    description: "Binding data.",
  });

export const BindingsIdDeleteRequestSchema = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: BindingsModelsDeleteRequestIdSchema,
  }),
  query: z.optional(z.never()),
});

/**
 * Request fulfilled, nothing follows
 */
export const BindingsIdDeleteResponseSchema = z
  .void()
  .register(z.globalRegistry, {
    description: "Request fulfilled, nothing follows",
  });

export const MediaIdDeleteRequestSchema = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: MediaModelsDeleteRequestIdSchema,
  }),
  query: z.optional(z.never()),
});

/**
 * Request fulfilled, nothing follows
 */
export const MediaIdDeleteResponseSchema = z.void().register(z.globalRegistry, {
  description: "Request fulfilled, nothing follows",
});

export const MediaIdContentDownloadRequestSchema = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: DownloadRequestIdSchema,
  }),
  query: z.optional(z.never()),
});

export const MediaIdContentHeaddownloadRequestSchema = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: DownloadRequestIdSchema,
  }),
  query: z.optional(z.never()),
});

export const MediaIdContentUploadRequestSchema = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: UploadRequestIdSchema,
  }),
  query: z.optional(z.never()),
  headers: z.object({
    "Content-Type": z.union([UploadRequestTypeSchema, z.string()]),
  }),
});

/**
 * Request fulfilled, nothing follows
 */
export const MediaIdContentUploadResponseSchema = z
  .void()
  .register(z.globalRegistry, {
    description: "Request fulfilled, nothing follows",
  });

export const PingPingRequestSchema = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful ping.
 */
export const PingPingResponseSchema = z.void().register(z.globalRegistry, {
  description: "Successful ping.",
});

export const PingHeadpingRequestSchema = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful ping.
 */
export const PingHeadpingResponseSchema = z.void().register(z.globalRegistry, {
  description: "Successful ping.",
});

export const PlaylistsIdDeleteRequestSchema = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: PlaylistsModelsDeleteRequestIdSchema,
  }),
  query: z.optional(z.never()),
});

/**
 * Request fulfilled, nothing follows
 */
export const PlaylistsIdDeleteResponseSchema = z
  .void()
  .register(z.globalRegistry, {
    description: "Request fulfilled, nothing follows",
  });

export const PlaylistsIdM3Um3uRequestSchema = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: M3uRequestIdSchema,
  }),
  query: z.optional(z.never()),
});

/**
 * Request fulfilled, document follows
 */
export const PlaylistsIdM3Um3uResponseSchema = z
  .string()
  .register(z.globalRegistry, {
    description: "Request fulfilled, document follows",
  });

export const PlaylistsIdM3uHeadm3uRequestSchema = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: HeadM3uRequestIdSchema,
  }),
  query: z.optional(z.never()),
});

export const SseSubscribeRequestSchema = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Stream of Server-Sent Events.
 */
export const SseSubscribeResponseSchema = z
  .string()
  .register(z.globalRegistry, {
    description: "Stream of Server-Sent Events.",
  });

export const TestTestRequestSchema = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      parameters: z.optional(
        z.union([TestRequestParametersSchema, z.string(), z.null()]),
      ),
    }),
  ),
});

/**
 * Request fulfilled, document follows
 */
export const TestTestResponseSchema = TestResponseResultSchema;

export const BindingsListRequestSchema = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      limit: z.optional(
        z.union([BindingsModelsListRequestLimitSchema, z.string(), z.null()]),
      ),
      offset: z.optional(
        z.union([BindingsModelsListRequestOffsetSchema, z.string(), z.null()]),
      ),
      where: z.optional(
        z.union([BindingsModelsListRequestWhereSchema, z.string(), z.null()]),
      ),
      include: z.optional(
        z.union([BindingsModelsListRequestIncludeSchema, z.string(), z.null()]),
      ),
      order: z.optional(
        z.union([BindingsModelsListRequestOrderSchema, z.string(), z.null()]),
      ),
    }),
  ),
});

/**
 * Request fulfilled, document follows
 */
export const BindingsListResponseSchema =
  BindingsModelsListResponseResultsSchema;

export const BindingsCreateRequestSchema = z.object({
  body: BindingsModelsCreateRequestDataSchema,
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      include: z.optional(
        z.union([
          BindingsModelsCreateRequestIncludeSchema,
          z.string(),
          z.null(),
        ]),
      ),
    }),
  ),
});

/**
 * Document created, URL follows
 */
export const BindingsCreateResponseSchema = BindingsModelsBindingSchema;

export const BindingsIdGetRequestSchema = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: BindingsModelsGetRequestIdSchema,
  }),
  query: z.optional(
    z.object({
      include: z.optional(
        z.union([BindingsModelsGetRequestIncludeSchema, z.string(), z.null()]),
      ),
    }),
  ),
});

/**
 * Request fulfilled, document follows
 */
export const BindingsIdGetResponseSchema = GetResponseBindingSchema;

export const BindingsIdUpdateRequestSchema = z.object({
  body: BindingsModelsUpdateRequestDataSchema,
  path: z.object({
    id: BindingsModelsUpdateRequestIdSchema,
  }),
  query: z.optional(
    z.object({
      include: z.optional(
        z.union([
          BindingsModelsUpdateRequestIncludeSchema,
          z.string(),
          z.null(),
        ]),
      ),
    }),
  ),
});

/**
 * Request fulfilled, document follows
 */
export const BindingsIdUpdateResponseSchema = BindingsModelsBindingSchema;

export const MediaListRequestSchema = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      limit: z.optional(
        z.union([MediaModelsListRequestLimitSchema, z.string(), z.null()]),
      ),
      offset: z.optional(
        z.union([MediaModelsListRequestOffsetSchema, z.string(), z.null()]),
      ),
      where: z.optional(
        z.union([MediaModelsListRequestWhereSchema, z.string(), z.null()]),
      ),
      include: z.optional(
        z.union([MediaModelsListRequestIncludeSchema, z.string(), z.null()]),
      ),
      order: z.optional(
        z.union([MediaModelsListRequestOrderSchema, z.string(), z.null()]),
      ),
    }),
  ),
});

/**
 * Request fulfilled, document follows
 */
export const MediaListResponseSchema = MediaModelsListResponseResultsSchema;

export const MediaCreateRequestSchema = z.object({
  body: MediaModelsCreateRequestDataSchema,
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      include: z.optional(
        z.union([MediaModelsCreateRequestIncludeSchema, z.string(), z.null()]),
      ),
    }),
  ),
});

/**
 * Document created, URL follows
 */
export const MediaCreateResponseSchema = MediaModelsMediaSchema;

export const MediaIdGetRequestSchema = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: MediaModelsGetRequestIdSchema,
  }),
  query: z.optional(
    z.object({
      include: z.optional(
        z.union([MediaModelsGetRequestIncludeSchema, z.string(), z.null()]),
      ),
    }),
  ),
});

/**
 * Request fulfilled, document follows
 */
export const MediaIdGetResponseSchema = GetResponseMediaSchema;

export const MediaIdUpdateRequestSchema = z.object({
  body: MediaModelsUpdateRequestDataSchema,
  path: z.object({
    id: MediaModelsUpdateRequestIdSchema,
  }),
  query: z.optional(
    z.object({
      include: z.optional(
        z.union([MediaModelsUpdateRequestIncludeSchema, z.string(), z.null()]),
      ),
    }),
  ),
});

/**
 * Request fulfilled, document follows
 */
export const MediaIdUpdateResponseSchema = MediaModelsMediaSchema;

export const PlaylistsListRequestSchema = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      limit: z.optional(
        z.union([PlaylistsModelsListRequestLimitSchema, z.string(), z.null()]),
      ),
      offset: z.optional(
        z.union([PlaylistsModelsListRequestOffsetSchema, z.string(), z.null()]),
      ),
      where: z.optional(
        z.union([PlaylistsModelsListRequestWhereSchema, z.string(), z.null()]),
      ),
      include: z.optional(
        z.union([
          PlaylistsModelsListRequestIncludeSchema,
          z.string(),
          z.null(),
        ]),
      ),
      order: z.optional(
        z.union([PlaylistsModelsListRequestOrderSchema, z.string(), z.null()]),
      ),
    }),
  ),
});

/**
 * Request fulfilled, document follows
 */
export const PlaylistsListResponseSchema =
  PlaylistsModelsListResponseResultsSchema;

export const PlaylistsCreateRequestSchema = z.object({
  body: PlaylistsModelsCreateRequestDataSchema,
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      include: z.optional(
        z.union([
          PlaylistsModelsCreateRequestIncludeSchema,
          z.string(),
          z.null(),
        ]),
      ),
    }),
  ),
});

/**
 * Document created, URL follows
 */
export const PlaylistsCreateResponseSchema = PlaylistsModelsPlaylistSchema;

export const PlaylistsIdGetRequestSchema = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: PlaylistsModelsGetRequestIdSchema,
  }),
  query: z.optional(
    z.object({
      include: z.optional(
        z.union([PlaylistsModelsGetRequestIncludeSchema, z.string(), z.null()]),
      ),
    }),
  ),
});

/**
 * Request fulfilled, document follows
 */
export const PlaylistsIdGetResponseSchema = GetResponsePlaylistSchema;

export const PlaylistsIdUpdateRequestSchema = z.object({
  body: PlaylistsModelsUpdateRequestDataSchema,
  path: z.object({
    id: PlaylistsModelsUpdateRequestIdSchema,
  }),
  query: z.optional(
    z.object({
      include: z.optional(
        z.union([
          PlaylistsModelsUpdateRequestIncludeSchema,
          z.string(),
          z.null(),
        ]),
      ),
    }),
  ),
});

/**
 * Request fulfilled, document follows
 */
export const PlaylistsIdUpdateResponseSchema = PlaylistsModelsPlaylistSchema;
