// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Playlist
 */
export type PlaylistsModelsPlaylist = {
  /**
   * Identifier of the playlist.
   */
  id: string;
  /**
   * Name of the playlist.
   */
  name: string;
  /**
   * Bindings that the playlist belongs to.
   */
  bindings?: Array<PlaylistsModelsBinding> | null;
};

/**
 * Binding
 */
export type PlaylistsModelsBinding = {
  /**
   * Identifier of the binding.
   */
  id: string;
  /**
   * Identifier of the playlist that the binding belongs to.
   */
  playlistId: string;
  /**
   * Identifier of the media that the binding belongs to.
   */
  mediaId: string;
  /**
   * Rank of the media in the binding.
   */
  rank: string;
  /**
   * Playlist that the binding belongs to.
   */
  playlist: unknown;
  /**
   * Media that the binding belongs to.
   */
  media: unknown;
};

/**
 * Media
 */
export type MediaModelsMedia = {
  /**
   * Identifier of the media.
   */
  id: string;
  /**
   * Name of the media.
   */
  name: string;
  /**
   * Bindings that the media belongs to.
   */
  bindings?: Array<MediaModelsBinding> | null;
};

/**
 * Binding
 */
export type MediaModelsBinding = {
  /**
   * Identifier of the binding.
   */
  id: string;
  /**
   * Identifier of the playlist that the binding belongs to.
   */
  playlistId: string;
  /**
   * Identifier of the media that the binding belongs to.
   */
  mediaId: string;
  /**
   * Rank of the media in the binding.
   */
  rank: string;
  /**
   * Playlist that the binding belongs to.
   */
  playlist: unknown;
  /**
   * Media that the binding belongs to.
   */
  media: unknown;
};

/**
 * Playlist
 */
export type BindingsModelsPlaylist = {
  /**
   * Identifier of the playlist.
   */
  id: string;
  /**
   * Name of the playlist.
   */
  name: string;
  /**
   * Bindings that the playlist belongs to.
   */
  bindings?: Array<unknown> | null;
};

/**
 * Media
 */
export type BindingsModelsMedia = {
  /**
   * Identifier of the media.
   */
  id: string;
  /**
   * Name of the media.
   */
  name: string;
  /**
   * Bindings that the media belongs to.
   */
  bindings?: Array<unknown> | null;
};

/**
 * Binding
 */
export type BindingsModelsBinding = {
  /**
   * Identifier of the binding.
   */
  id: string;
  /**
   * Identifier of the playlist that the binding belongs to.
   */
  playlistId: string;
  /**
   * Identifier of the media that the binding belongs to.
   */
  mediaId: string;
  /**
   * Rank of the media in the binding.
   */
  rank: string;
  /**
   * Playlist that the binding belongs to.
   */
  playlist?: BindingsModelsPlaylist | null;
  /**
   * Media that the binding belongs to.
   */
  media?: BindingsModelsMedia | null;
};

/**
 * PlaylistUpdateInput
 *
 * Data to update a playlist.
 */
export type PlaylistUpdateInput = {
  id?: string;
  name?: string;
};

/**
 * PlaylistList
 */
export type PlaylistList = {
  /**
   * Total number of playlists that matched the query.
   */
  count: number;
  /**
   * Maximum number of returned playlists.
   */
  limit?: number | null;
  /**
   * Number of playlists skipped.
   */
  offset?: number | null;
  /**
   * Playlists that matched the request.
   */
  playlists: Array<PlaylistsModelsPlaylist>;
};

/**
 * PlaylistCreateInput
 *
 * Data to create a playlist.
 */
export type PlaylistCreateInput = {
  id?: string;
  name: string;
};

/**
 * MediaUpdateInput
 *
 * Data to update media.
 */
export type MediaUpdateInput = {
  id?: string;
  name?: string;
};

/**
 * MediaList
 */
export type MediaList = {
  /**
   * Total number of media that matched the query.
   */
  count: number;
  /**
   * Maximum number of returned media.
   */
  limit?: number | null;
  /**
   * Number of media skipped.
   */
  offset?: number | null;
  /**
   * Media that matched the request.
   */
  media: Array<MediaModelsMedia>;
};

/**
 * MediaCreateInput
 *
 * Data to create media.
 */
export type MediaCreateInput = {
  id?: string;
  name: string;
};

/**
 * BindingUpdateInput
 *
 * Data to update a binding.
 */
export type BindingUpdateInput = {
  id?: string;
  rank?: string;
};

/**
 * BindingList
 */
export type BindingList = {
  /**
   * Total number of bindings that matched the query.
   */
  count: number;
  /**
   * Maximum number of returned bindings.
   */
  limit?: number | null;
  /**
   * Number of bindings skipped.
   */
  offset?: number | null;
  /**
   * Bindings that matched the request.
   */
  bindings: Array<BindingsModelsBinding>;
};

/**
 * BindingCreateInput
 *
 * Data to create a binding.
 */
export type BindingCreateInput = {
  id?: string;
  playlistId: string;
  mediaId: string;
  rank: string;
};

export type BindingsListRequest = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Maximum number of bindings to return.
     */
    limit?: number | null;
    /**
     * Number of bindings to skip.
     */
    offset?: number | null;
    /**
     * Filter to apply to find bindings.
     */
    where?: string | null;
    /**
     * Relations to include in the response.
     */
    include?: string | null;
    /**
     * Order to apply to the results.
     */
    order?: string | null;
  };
  url: "/bindings";
};

export type BindingsListErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type BindingsListError = BindingsListErrors[keyof BindingsListErrors];

export type BindingsListResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: BindingList;
};

export type BindingsListResponse =
  BindingsListResponses[keyof BindingsListResponses];

export type BindingsCreateRequest = {
  body: BindingCreateInput;
  path?: never;
  query?: {
    /**
     * Relations to include in the response.
     */
    include?: string | null;
  };
  url: "/bindings";
};

export type BindingsCreateErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type BindingsCreateError =
  BindingsCreateErrors[keyof BindingsCreateErrors];

export type BindingsCreateResponses = {
  /**
   * Document created, URL follows
   */
  201: BindingsModelsBinding;
};

export type BindingsCreateResponse =
  BindingsCreateResponses[keyof BindingsCreateResponses];

export type BindingsIdDeleteRequest = {
  body?: never;
  path: {
    /**
     * Identifier of the binding to delete.
     */
    id: string;
  };
  query?: never;
  url: "/bindings/{id}";
};

export type BindingsIdDeleteErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type BindingsIdDeleteError =
  BindingsIdDeleteErrors[keyof BindingsIdDeleteErrors];

export type BindingsIdDeleteResponses = {
  /**
   * Request fulfilled, nothing follows
   */
  204: void;
};

export type BindingsIdDeleteResponse =
  BindingsIdDeleteResponses[keyof BindingsIdDeleteResponses];

export type BindingsIdGetRequest = {
  body?: never;
  path: {
    /**
     * Identifier of the binding to get.
     */
    id: string;
  };
  query?: {
    /**
     * Relations to include in the response.
     */
    include?: string | null;
  };
  url: "/bindings/{id}";
};

export type BindingsIdGetErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type BindingsIdGetError = BindingsIdGetErrors[keyof BindingsIdGetErrors];

export type BindingsIdGetResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: BindingsModelsBinding;
};

export type BindingsIdGetResponse =
  BindingsIdGetResponses[keyof BindingsIdGetResponses];

export type BindingsIdUpdateRequest = {
  body: BindingUpdateInput;
  path: {
    /**
     * Identifier of the binding to update.
     */
    id: string;
  };
  query?: {
    /**
     * Relations to include in the response.
     */
    include?: string | null;
  };
  url: "/bindings/{id}";
};

export type BindingsIdUpdateErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type BindingsIdUpdateError =
  BindingsIdUpdateErrors[keyof BindingsIdUpdateErrors];

export type BindingsIdUpdateResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: BindingsModelsBinding;
};

export type BindingsIdUpdateResponse =
  BindingsIdUpdateResponses[keyof BindingsIdUpdateResponses];

export type MediaListRequest = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Maximum number of media to return.
     */
    limit?: number | null;
    /**
     * Number of media to skip.
     */
    offset?: number | null;
    /**
     * Filter to apply to find media.
     */
    where?: string | null;
    /**
     * Relations to include in the response.
     */
    include?: string | null;
    /**
     * Order to apply to the results.
     */
    order?: string | null;
  };
  url: "/media";
};

export type MediaListErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type MediaListError = MediaListErrors[keyof MediaListErrors];

export type MediaListResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: MediaList;
};

export type MediaListResponse = MediaListResponses[keyof MediaListResponses];

export type MediaCreateRequest = {
  body: MediaCreateInput;
  path?: never;
  query?: {
    /**
     * Relations to include in the response.
     */
    include?: string | null;
  };
  url: "/media";
};

export type MediaCreateErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type MediaCreateError = MediaCreateErrors[keyof MediaCreateErrors];

export type MediaCreateResponses = {
  /**
   * Document created, URL follows
   */
  201: MediaModelsMedia;
};

export type MediaCreateResponse =
  MediaCreateResponses[keyof MediaCreateResponses];

export type MediaIdDeleteRequest = {
  body?: never;
  path: {
    /**
     * Identifier of the media to delete.
     */
    id: string;
  };
  query?: never;
  url: "/media/{id}";
};

export type MediaIdDeleteErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type MediaIdDeleteError = MediaIdDeleteErrors[keyof MediaIdDeleteErrors];

export type MediaIdDeleteResponses = {
  /**
   * Request fulfilled, nothing follows
   */
  204: void;
};

export type MediaIdDeleteResponse =
  MediaIdDeleteResponses[keyof MediaIdDeleteResponses];

export type MediaIdGetRequest = {
  body?: never;
  path: {
    /**
     * Identifier of the media to get.
     */
    id: string;
  };
  query?: {
    /**
     * Relations to include in the response.
     */
    include?: string | null;
  };
  url: "/media/{id}";
};

export type MediaIdGetErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type MediaIdGetError = MediaIdGetErrors[keyof MediaIdGetErrors];

export type MediaIdGetResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: MediaModelsMedia;
};

export type MediaIdGetResponse = MediaIdGetResponses[keyof MediaIdGetResponses];

export type MediaIdUpdateRequest = {
  body: MediaUpdateInput;
  path: {
    /**
     * Identifier of the media to update.
     */
    id: string;
  };
  query?: {
    /**
     * Relations to include in the response.
     */
    include?: string | null;
  };
  url: "/media/{id}";
};

export type MediaIdUpdateErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type MediaIdUpdateError = MediaIdUpdateErrors[keyof MediaIdUpdateErrors];

export type MediaIdUpdateResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: MediaModelsMedia;
};

export type MediaIdUpdateResponse =
  MediaIdUpdateResponses[keyof MediaIdUpdateResponses];

export type MediaIdContentDownloadRequest = {
  body?: never;
  path: {
    /**
     * Identifier of the media to download content for.
     */
    id: string;
  };
  query?: never;
  url: "/media/{id}/content";
};

export type MediaIdContentDownloadErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type MediaIdContentDownloadError =
  MediaIdContentDownloadErrors[keyof MediaIdContentDownloadErrors];

export type MediaIdContentDownloadResponses = {
  /**
   * Request fulfilled, stream follows
   */
  200: unknown;
};

export type MediaIdContentHeaddownloadRequest = {
  body?: never;
  path: {
    /**
     * Identifier of the media to get content headers for.
     */
    id: string;
  };
  query?: never;
  url: "/media/{id}/content";
};

export type MediaIdContentHeaddownloadErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type MediaIdContentHeaddownloadError =
  MediaIdContentHeaddownloadErrors[keyof MediaIdContentHeaddownloadErrors];

export type MediaIdContentHeaddownloadResponses = {
  /**
   * Request fulfilled, nothing follows
   */
  200: unknown;
};

export type MediaIdContentUploadRequest = {
  body?: never;
  headers: {
    /**
     * Content type.
     */
    "Content-Type": string;
  };
  path: {
    /**
     * Identifier of the media to upload content for.
     */
    id: string;
  };
  query?: never;
  url: "/media/{id}/content";
};

export type MediaIdContentUploadErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type MediaIdContentUploadError =
  MediaIdContentUploadErrors[keyof MediaIdContentUploadErrors];

export type MediaIdContentUploadResponses = {
  /**
   * Request fulfilled, nothing follows
   */
  204: void;
};

export type MediaIdContentUploadResponse =
  MediaIdContentUploadResponses[keyof MediaIdContentUploadResponses];

export type PingPingRequest = {
  body?: never;
  path?: never;
  query?: never;
  url: "/ping";
};

export type PingPingResponses = {
  /**
   * Successful ping.
   */
  204: void;
};

export type PingPingResponse = PingPingResponses[keyof PingPingResponses];

export type PingHeadpingRequest = {
  body?: never;
  path?: never;
  query?: never;
  url: "/ping";
};

export type PingHeadpingResponses = {
  /**
   * Successful ping.
   */
  204: void;
};

export type PingHeadpingResponse =
  PingHeadpingResponses[keyof PingHeadpingResponses];

export type PlaylistsListRequest = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Maximum number of playlists to return.
     */
    limit?: number | null;
    /**
     * Number of playlists to skip.
     */
    offset?: number | null;
    /**
     * Filter to apply to find playlists.
     */
    where?: string | null;
    /**
     * Relations to include in the response.
     */
    include?: string | null;
    /**
     * Order to apply to the results.
     */
    order?: string | null;
  };
  url: "/playlists";
};

export type PlaylistsListErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type PlaylistsListError = PlaylistsListErrors[keyof PlaylistsListErrors];

export type PlaylistsListResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: PlaylistList;
};

export type PlaylistsListResponse =
  PlaylistsListResponses[keyof PlaylistsListResponses];

export type PlaylistsCreateRequest = {
  body: PlaylistCreateInput;
  path?: never;
  query?: {
    /**
     * Relations to include in the response.
     */
    include?: string | null;
  };
  url: "/playlists";
};

export type PlaylistsCreateErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type PlaylistsCreateError =
  PlaylistsCreateErrors[keyof PlaylistsCreateErrors];

export type PlaylistsCreateResponses = {
  /**
   * Document created, URL follows
   */
  201: PlaylistsModelsPlaylist;
};

export type PlaylistsCreateResponse =
  PlaylistsCreateResponses[keyof PlaylistsCreateResponses];

export type PlaylistsIdDeleteRequest = {
  body?: never;
  path: {
    /**
     * Identifier of the playlist to delete.
     */
    id: string;
  };
  query?: never;
  url: "/playlists/{id}";
};

export type PlaylistsIdDeleteErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type PlaylistsIdDeleteError =
  PlaylistsIdDeleteErrors[keyof PlaylistsIdDeleteErrors];

export type PlaylistsIdDeleteResponses = {
  /**
   * Request fulfilled, nothing follows
   */
  204: void;
};

export type PlaylistsIdDeleteResponse =
  PlaylistsIdDeleteResponses[keyof PlaylistsIdDeleteResponses];

export type PlaylistsIdGetRequest = {
  body?: never;
  path: {
    /**
     * Identifier of the playlist to get.
     */
    id: string;
  };
  query?: {
    /**
     * Relations to include in the response.
     */
    include?: string | null;
  };
  url: "/playlists/{id}";
};

export type PlaylistsIdGetErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type PlaylistsIdGetError =
  PlaylistsIdGetErrors[keyof PlaylistsIdGetErrors];

export type PlaylistsIdGetResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: PlaylistsModelsPlaylist;
};

export type PlaylistsIdGetResponse =
  PlaylistsIdGetResponses[keyof PlaylistsIdGetResponses];

export type PlaylistsIdUpdateRequest = {
  body: PlaylistUpdateInput;
  path: {
    /**
     * Identifier of the playlist to update.
     */
    id: string;
  };
  query?: {
    /**
     * Relations to include in the response.
     */
    include?: string | null;
  };
  url: "/playlists/{id}";
};

export type PlaylistsIdUpdateErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type PlaylistsIdUpdateError =
  PlaylistsIdUpdateErrors[keyof PlaylistsIdUpdateErrors];

export type PlaylistsIdUpdateResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: PlaylistsModelsPlaylist;
};

export type PlaylistsIdUpdateResponse =
  PlaylistsIdUpdateResponses[keyof PlaylistsIdUpdateResponses];

export type PlaylistsIdM3Um3uRequest = {
  body?: never;
  path: {
    /**
     * Identifier of the playlist to get.
     */
    id: string;
  };
  query?: never;
  url: "/playlists/{id}/m3u";
};

export type PlaylistsIdM3Um3uErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type PlaylistsIdM3Um3uError =
  PlaylistsIdM3Um3uErrors[keyof PlaylistsIdM3Um3uErrors];

export type PlaylistsIdM3Um3uResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: string;
};

export type PlaylistsIdM3Um3uResponse =
  PlaylistsIdM3Um3uResponses[keyof PlaylistsIdM3Um3uResponses];

export type PlaylistsIdM3uHeadm3uRequest = {
  body?: never;
  path: {
    /**
     * Identifier of the playlist to get.
     */
    id: string;
  };
  query?: never;
  url: "/playlists/{id}/m3u";
};

export type PlaylistsIdM3uHeadm3uErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type PlaylistsIdM3uHeadm3uError =
  PlaylistsIdM3uHeadm3uErrors[keyof PlaylistsIdM3uHeadm3uErrors];

export type PlaylistsIdM3uHeadm3uResponses = {
  /**
   * Request fulfilled, nothing follows
   */
  200: unknown;
};

export type SseSubscribeRequest = {
  body?: never;
  path?: never;
  query?: never;
  url: "/sse";
};

export type SseSubscribeResponses = {
  /**
   * Stream of Server-Sent Events.
   */
  200: string;
};

export type SseSubscribeResponse =
  SseSubscribeResponses[keyof SseSubscribeResponses];
